export const allOrders = [
    {
        id: 1, 
        flowerId: 'F101', 
        userId: 'U001', 
        phoneNumber: '0123456789', 
        paymentMethod: 'VNPay', 
        deliveryMethod: 'Standard Shipping', 
        createdDate: '2024-10-01', 
        address: '123 Flower Street, City A', 
        total: 2000000, 
        status: 'completed', 
        shopName: 'Birthday Blooms', 
        productName: 'Birthday Flower', 
        quantity: 5, 
        imageUrl: '/birthday/bi1.jpg',
        category: 'birthday'
    },
    {
        id: 2, 
        flowerId: 'F102', 
        userId: 'U002', 
        phoneNumber: '0987654321', 
        paymentMethod: 'VNPay', 
        deliveryMethod: 'Express Shipping', 
        createdDate: '2024-10-02', 
        address: '456 Celebration Ave, City B', 
        total: 1050000, 
        status: 'pending', 
        shopName: 'Celebration Garden', 
        productName: 'Birthday Flower', 
        quantity: 3, 
        imageUrl: '/birthday/bi2.jpg',
        category: 'birthday'
    },
    {
        id: 3, 
        flowerId: 'F103', 
        userId: 'U003', 
        phoneNumber: '0112233445', 
        paymentMethod: 'PayPal', 
        deliveryMethod: 'VNPay', 
        createdDate: '2024-10-03', 
        address: '789 Joyful Lane, City C', 
        total: 4500000, 
        status: 'shipping', 
        shopName: 'Joyful Petals', 
        productName: 'Birthday Flower 3', 
        quantity: 10, 
        imageUrl: '/birthday/bi3.jpg' ,
        category: 'birthday'
    },
    {
        id: 4, 
        flowerId: 'F104', 
        userId: 'U004', 
        phoneNumber: '0116677889', 
        paymentMethod: 'VNPay', 
        deliveryMethod: 'Standard Shipping', 
        createdDate: '2024-09-25', 
        address: '234 Wedding St, City D', 
        total: 100000, 
        status: 'canceled', 
        shopName: 'Elegant Wishes', 
        productName: 'Wedding Flower 1', 
        quantity: 1, 
        imageUrl: '/wedding/wedding1.jpg' ,
        category: 'wedding'
    },
    {
        id: 5, 
        flowerId: 'F105', 
        userId: 'U005', 
        phoneNumber: '0223344556', 
        paymentMethod: 'VNPay', 
        deliveryMethod: 'Express Shipping', 
        createdDate: '2024-09-26', 
        address: '567 Blossom Road, City E', 
        total: 240000, 
        status: 'returned', 
        shopName: 'Blossom Moments', 
        productName: 'Wedding Flower 2', 
        quantity: 2, 
        imageUrl: '/wedding/wedding2.jpg' ,
        category: 'wedding'
    },
    {
        id: 6, 
        flowerId: 'F106', 
        userId: 'U006', 
        phoneNumber: '0334455667', 
        paymentMethod: 'VNPay', 
        deliveryMethod: 'Standard Shipping', 
        createdDate: '2024-09-27', 
        address: '890 Floral Ave, City F', 
        total: 450000, 
        status: 'shipping', 
        shopName: 'Floral Cheers', 
        productName: 'Wedding Flower 3', 
        quantity: 3, 
        imageUrl: '/wedding/wedding3.jpg' ,
        category: 'wedding'
    },
    {
        id: 7, 
        flowerId: 'F107', 
        userId: 'U007', 
        phoneNumber: '0445566778', 
        paymentMethod: 'VNPay', 
        deliveryMethod: 'Standard Shipping', 
        createdDate: '2024-08-30', 
        address: '456 Festive Blvd, City G', 
        total: 100000, 
        status: 'delivery', 
        shopName: 'Festive Blooms', 
        productName: 'Holiday Flower 1', 
        quantity: 1, 
        imageUrl: '/holiday/ho1.jpg' ,
        category: 'holiday'
    },
    {
        id: 8, 
        flowerId: 'F108', 
        userId: 'U008', 
        phoneNumber: '0556677889', 
        paymentMethod: 'VNPay', 
        deliveryMethod: 'Express Shipping', 
        createdDate: '2024-08-31', 
        address: '789 Prestige St, City H', 
        total: 300000, 
        status: 'returned', 
        shopName: 'Prestige Petals', 
        productName: 'Holiday Flower 2', 
        quantity: 2, 
        imageUrl: '/holiday/ho2.jpg' ,
        category: 'holiday'
    },
    {
        id: 9, 
        flowerId: 'F109', 
        userId: 'U009', 
        phoneNumber: '0667788990', 
        paymentMethod: 'VNPay', 
        deliveryMethod: 'Same Day Delivery', 
        createdDate: '2024-09-01', 
        address: '345 Uplift St, City I', 
        total: 180000, 
        status: 'canceled', 
        shopName: 'Uplift Blooms', 
        productName: 'Holiday Flower 3', 
        quantity: 3, 
        imageUrl: '/holiday/ho3.jpg' ,
        category: 'holiday'
    },
    {
        id: 10, 
        flowerId: 'F110', 
        userId: 'U010', 
        phoneNumber: '0778899001', 
        paymentMethod: 'VNPay', 
        deliveryMethod: 'Standard Shipping', 
        createdDate: '2024-07-15', 
        address: '678 Happy Lane, City J', 
        total: 80000, 
        status: 'pending', 
        shopName: 'Happy Blossoms', 
        productName: 'Congratulatory Flower 1', 
        quantity: 1, 
        imageUrl: '/congratulate/con1.jpg',
        category: 'congratulate' 
    },
    {
        id: 11, 
        flowerId: 'F111', 
        userId: 'U011', 
        phoneNumber: '0889900112', 
        paymentMethod: 'VNPay', 
        deliveryMethod: 'Express Shipping', 
        createdDate: '2024-07-16', 
        address: '789 Tranquil St, City K', 
        total: 180000, 
        status: 'delivery', 
        shopName: 'Tranquil Garden', 
        productName: 'Congratulatory Flower 2', 
        quantity: 2, 
        imageUrl: '/congratulate/con2.jpg' ,
        category: 'congratulate'
    },
    {
        id: 12, 
        flowerId: 'F112', 
        userId: 'U012', 
        phoneNumber: '0990011223', 
        paymentMethod: 'VNPay', 
        deliveryMethod: 'Standard Shipping', 
        createdDate: '2024-07-17', 
        address: '123 Golden Ave, City L', 
        total: 270000, 
        status: 'completed', 
        shopName: 'Golden Joy', 
        productName: 'Congratulatory Flower 3', 
        quantity: 3, 
        imageUrl: '/congratulate/con3.jpg' ,
        category: 'congratulate'
    },
    {
        id: 13, 
        flowerId: 'F113', 
        userId: 'U013', 
        phoneNumber: '0112233446', 
        paymentMethod: 'VNPay', 
        deliveryMethod: 'Same Day Delivery', 
        createdDate: '2024-06-10', 
        address: '345 Sweet Lane, City M', 
        total: 70000, 
        status: 'pending', 
        shopName: 'Sweet Blooms', 
        productName: 'Rose 1', 
        quantity: 1, 
        imageUrl: '/roses/rose1.jpg' ,
        category: 'rose'
    },
    {
        id: 14, 
        flowerId: 'F114', 
        userId: 'U014', 
        phoneNumber: '0223344557', 
        paymentMethod: 'VNPay', 
        deliveryMethod: 'Standard Shipping', 
        createdDate: '2024-06-11', 
        address: '789 Colorful Blvd, City N', 
        total: 140000, 
        status: 'canceled', 
        shopName: 'Colorful Celebrations', 
        productName: 'Roses 2', 
        quantity: 2, 
        imageUrl: '/roses/rose2.jpg' ,
        category: 'rose'
    },
    {
        id: 15, 
        flowerId: 'F115', 
        userId: 'U015', 
        phoneNumber: '0334455668', 
        paymentMethod: 'VNPay', 
        deliveryMethod: 'Express Shipping', 
        createdDate: '2024-06-12', 
        address: '234 Elegant Lane, City O', 
        total: 240000, 
        status: 'returned', 
        shopName: 'Elegant Celebrations', 
        productName: 'Rose 3', 
        quantity: 3, 
        imageUrl: '/roses/rose3.jpg' ,
        category: 'rose'
    },
    {
        id: 16, 
        flowerId: 'F116', 
        userId: 'U016', 
        phoneNumber: '0445566779', 
        paymentMethod: 'VNPay', 
        deliveryMethod: 'Standard Shipping', 
        createdDate: '2024-12-01', 
        address: '567 Youthful St, City P', 
        total: 110000, 
        status: 'completed', 
        shopName: 'Youthful Blooms', 
        productName: 'Orchid 1', 
        quantity: 1, 
        imageUrl: '/orchid/o1.jpg' ,
        category: 'orchid'
    },
    {
        id: 17, 
        flowerId: 'F117', 
        userId: 'U017', 
        phoneNumber: '0556677880', 
        paymentMethod: 'VNPay', 
        deliveryMethod: 'Express Shipping', 
        createdDate: '2024-12-02', 
        address: '890 Refreshing Ave, City Q', 
        total: 150000, 
        status: 'pending', 
        shopName: 'Refreshing Celebrations', 
        productName: 'Orchid 2', 
        quantity: 2, 
        imageUrl: '/orchid/o2.jpg' ,
        category: 'orchid'
    },
    {
        id: 18, 
        flowerId: 'F118', 
        userId: 'U018', 
        phoneNumber: '0667788991', 
        paymentMethod: 'VNPay', 
        deliveryMethod: 'Same Day Delivery', 
        createdDate: '2024-12-03', 
        address: '345 Christmas Ave, City R', 
        total: 360000, 
        status: 'shipping', 
        shopName: 'Christmas Flower', 
        productName: 'Orchid 3', 
        quantity: 3, 
        imageUrl: '/orchid/o3.jpg' ,
        category: 'orchid'
    },
    {
        id: 19, 
        flowerId: 'F119', 
        userId: 'U019', 
        phoneNumber: '0778899002', 
        paymentMethod: 'VNPay', 
        deliveryMethod: 'Standard Shipping', 
        createdDate: '2024-01-05', 
        address: '123 Pastel Lane, City S', 
        total: 95000, 
        status: 'completed', 
        shopName: 'Pastel Dreams', 
        productName: 'Table Flower 1', 
        quantity: 1, 
        imageUrl: '/table/table1.jpg',
        category: 'table' 
    },
    {
        id: 20, 
        flowerId: 'F120', 
        userId: 'U020', 
        phoneNumber: '0889900113', 
        paymentMethod: 'VNPay', 
        deliveryMethod: 'Express Shipping', 
        createdDate: '2024-01-06', 
        address: '789 Fragrant Blvd, City T', 
        total: 200000, 
        status: 'pending', 
        shopName: 'Fragrant Blossoms', 
        productName: 'Table Flower 2', 
        quantity: 2, 
        imageUrl: '/table/table2.jpg' ,
        category: 'table'
    }
];
