export const sellerData = [
  {
      Id: 1,
      name: "FLORA",
      logo: "/image/Logo-shop-hoa-2.jpg",
      address: "123 Flower Street, District 1, Ho Chi Minh City",
      type: "Seller",
      created_at: "2020-05-02",
      updated_at: "2022-07-14",
      role: "individual",
      introduction: "FLORA is a premium flower shop specializing in a wide range of flowers for all occasions, including birthdays, holidays, and special events. With 4 years of experience, FLORA is committed to providing beautiful, fresh flowers and excellent customer service.",
      products: [
          { id: 1, name: "Rose 1", price: "400,000VND", image: "/roses/rose1.jpg" },
          { id: 2, name: "Birthday Flower", price: "500,000VND", image: "/birthday/bi1.jpg" },
          { id: 3, name: "Rose 2", price: "600,000VND", image: "/roses/rose2.jpg" },
          { id: 4, name: "Holiday Flower", price: "350,000VND", image: "/holiday/ho1.jpg" },
          { id: 5, name: "Orchid", price: "400,000VND", image: "/orchid/o12.jpg" },
          { id: 6, name: "Congratulate Flower", price: "400,000VND", image: "/congratulate/con15.jpg" },
          { id: 7, name: "Table Flower", price: "300,000VND", image: "/table/table18.jpg" },
          { id: 8, name: "Birthday Flower 2", price: "500,000VND", image: "/birthday/bi7.jpg" },
      ],
  },
  {
      Id: 2,
      name: "SENTIMENT",
      logo: "/image/logo2.jpg",
      address: "456 Sentiment Avenue, District 3, Ho Chi Minh City",
      type: "Seller",
      created_at: "2019-07-15",
      updated_at: "2021-11-30",
      role: "individual",
      introduction: "SENTIMENT offers a beautiful collection of handcrafted floral arrangements for every occasion. We pride ourselves on our attention to detail and commitment to customer satisfaction.",
      products: [
          { id: 1, name: "Rose 1", price: "400,000VND", image: "/roses/rose15.jpg" },
          { id: 2, name: "Birthday Flower", price: "500,000VND", image: "/birthday/bi11.jpg" },
          { id: 3, name: "Rose 2", price: "600,000VND", image: "/roses/rose9.jpg" },
          { id: 4, name: "Holiday Flower", price: "350,000VND", image: "/holiday/ho3.jpg" },
          { id: 5, name: "Orchid", price: "400,000VND", image: "/orchid/o14.jpg" },
          { id: 6, name: "Congratulate Flower", price: "400,000VND", image: "/congratulate/con12.jpg" },
          { id: 7, name: "Table Flower", price: "300,000VND", image: "/table/table14.jpg" },
          { id: 8, name: "Birthday Flower 2", price: "500,000VND", image: "/birthday/bi3.jpg" },
      ],
  },
  {
      Id: 3,
      name: "DARIANA",
      logo: "/image/logo3.png",
      address: "789 Dariana Street, District 5, Ho Chi Minh City",
      type: "Seller",
      created_at: "2017-03-10",
      updated_at: "2021-09-20",
      role: "enterprise",
      introduction: "DARIANA is known for its exotic flower arrangements, perfect for corporate events, weddings, and other grand celebrations. With over 5 years of experience, we aim to provide flowers that leave lasting impressions.",
      products: [
          { id: 1, name: "Rose 1", price: "400,000VND", image: "/roses/rose2.jpg" },
          { id: 2, name: "Birthday Flower", price: "500,000VND", image: "/birthday/bi7.jpg" },
          { id: 3, name: "Rose 2", price: "600,000VND", image: "/roses/rose6.jpg" },
          { id: 4, name: "Holiday Flower", price: "350,000VND", image: "/holiday/ho9.jpg" },
          { id: 5, name: "Orchid", price: "400,000VND", image: "/orchid/o3.jpg" },
          { id: 6, name: "Congratulate Flower", price: "400,000VND", image: "/congratulate/con12.jpg" },
          { id: 7, name: "Table Flower", price: "300,000VND", image: "/table/table17.jpg" },
          { id: 8, name: "Birthday Flower 2", price: "500,000VND", image: "/birthday/bi8.jpg" },
      ],
  },
  {
      Id: 4,
      name: "FLORIFFIC",
      logo: "/image/logo4.png",
      address: "12 Floriffic Road, District 2, Ho Chi Minh City",
      type: "Seller",
      created_at: "2018-04-18",
      updated_at: "2022-01-02",
      role: "company",
      introduction: "FLORIFFIC specializes in vibrant and elegant floral designs for any celebration, from birthdays to grand openings. We offer fresh, high-quality flowers with an emphasis on style and elegance.",
      products: [
          { id: 1, name: "Rose 1", price: "400,000VND", image: "/roses/rose4.jpg" },
          { id: 2, name: "Birthday Flower", price: "500,000VND", image: "/birthday/bi4.jpg" },
          { id: 3, name: "Rose 2", price: "600,000VND", image: "/roses/rose4.jpg" },
          { id: 4, name: "Holiday Flower", price: "350,000VND", image: "/holiday/ho4.jpg" },
          { id: 5, name: "Orchid", price: "400,000VND", image: "/orchid/o4.jpg" },
          { id: 6, name: "Congratulate Flower", price: "400,000VND", image: "/congratulate/con4.jpg" },
          { id: 7, name: "Table Flower", price: "300,000VND", image: "/table/table4.jpg" },
          { id: 8, name: "Birthday Flower 2", price: "500,000VND", image: "/birthday/bi4.jpg" },
      ],
  },
  {
      Id: 5,
      name: "FLORAL FANTASY",
      logo: "/image/logo5.jpg",
      address: "456 Floral Road, District 7, Ho Chi Minh City",
      type: "Seller",
      created_at: "2021-02-22",
      updated_at: "2022-05-10",
      role: "individual",
      introduction: "FLORAL FANTASY offers whimsical floral designs for those looking for something creative and unique. Our flowers are fresh, beautiful, and perfect for any occasion.",
      products: [
          { id: 1, name: "Rose 1", price: "400,000VND", image: "/roses/rose5.jpg" },
          { id: 2, name: "Birthday Flower", price: "500,000VND", image: "/birthday/bi5.jpg" },
          { id: 3, name: "Rose 2", price: "600,000VND", image: "/roses/rose5.jpg" },
          { id: 4, name: "Holiday Flower", price: "350,000VND", image: "/holiday/ho5.jpg" },
          { id: 5, name: "Orchid", price: "400,000VND", image: "/orchid/o5.jpg" },
          { id: 6, name: "Congratulate Flower", price: "400,000VND", image: "/congratulate/con5.jpg" },
          { id: 7, name: "Table Flower", price: "300,000VND", image: "/table/table5.jpg" },
          { id: 8, name: "Birthday Flower 2", price: "500,000VND", image: "/birthday/bi5.jpg" },
      ],
  },
  {
      Id: 6,
      name: "PENNY",
      logo: "/image/logo6.jpg",
      address: "789 Penny Lane, District 8, Ho Chi Minh City",
      type: "Seller",
      created_at: "2019-06-30",
      updated_at: "2021-12-05",
      role: "enterprise",
      introduction: "PENNY brings nature to life with fresh and vibrant flower arrangements that brighten any room. We are passionate about creating beautiful designs that speak to your heart.",
      products: [
          { id: 1, name: "Rose 1", price: "400,000VND", image: "/roses/rose6.jpg" },
          { id: 2, name: "Birthday Flower", price: "500,000VND", image: "/birthday/bi6.jpg" },
          { id: 3, name: "Rose 2", price: "600,000VND", image: "/roses/rose6.jpg" },
          { id: 4, name: "Holiday Flower", price: "350,000VND", image: "/holiday/ho6.jpg" },
          { id: 5, name: "Orchid", price: "400,000VND", image: "/orchid/o6.jpg" },
          { id: 6, name: "Congratulate Flower", price: "400,000VND", image: "/congratulate/con6.jpg" },
          { id: 7, name: "Table Flower", price: "300,000VND", image: "/table/table6.jpg" },
          { id: 8, name: "Birthday Flower 2", price: "500,000VND", image: "/birthday/bi6.jpg" },
      ],
  },
  {
      Id: 7,
      name: "CAROLINA PETALS",
      logo: "/image/logo7.jpg",
      address: "123 Petal Street, District 9, Ho Chi Minh City",
      type: "Seller",
      created_at: "2018-11-02",
      updated_at: "2022-03-25",
      role: "individual",
      introduction: "CAROLINA PETALS offers timeless, classic floral arrangements for weddings, corporate events, and everyday occasions. We strive to make every arrangement unique and unforgettable.",
      products: [
          { id: 1, name: "Rose 1", price: "400,000VND", image: "/roses/rose7.jpg" },
          { id: 2, name: "Birthday Flower", price: "500,000VND", image: "/birthday/bi7.jpg" },
          { id: 3, name: "Rose 2", price: "600,000VND", image: "/roses/rose7.jpg" },
          { id: 4, name: "Holiday Flower", price: "350,000VND", image: "/holiday/ho7.jpg" },
          { id: 5, name: "Orchid", price: "400,000VND", image: "/orchid/o7.jpg" },
          { id: 6, name: "Congratulate Flower", price: "400,000VND", image: "/congratulate/con7.jpg" },
          { id: 7, name: "Table Flower", price: "300,000VND", image: "/table/table7.jpg" },
          { id: 8, name: "Birthday Flower 2", price: "500,000VND", image: "/birthday/bi10.jpg" },
      ],
  },
  {
      Id: 8,
      name: "CEDAR HOUSE",
      logo: "/image/logo8.jpg",
      address: "456 Cedar Lane, District 10, Ho Chi Minh City",
      type: "Seller",
      created_at: "2017-09-08",
      updated_at: "2021-11-18",
      role: "enterprise",
      introduction: "CEDAR HOUSE brings natural beauty to your home and events with fresh, stylish floral arrangements. We believe flowers should inspire and bring joy to every moment.",
      products: [
          { id: 1, name: "Rose 1", price: "400,000VND", image: "/roses/rose8.jpg" },
          { id: 2, name: "Birthday Flower", price: "500,000VND", image: "/birthday/bi8.jpg" },
          { id: 3, name: "Rose 2", price: "600,000VND", image: "/roses/rose8.jpg" },
          { id: 4, name: "Holiday Flower", price: "350,000VND", image: "/holiday/ho8.jpg" },
          { id: 5, name: "Orchid", price: "400,000VND", image: "/orchid/o8.jpg" },
          { id: 6, name: "Congratulate Flower", price: "400,000VND", image: "/congratulate/con8.jpg" },
          { id: 7, name: "Table Flower", price: "300,000VND", image: "/table/table8.jpg" },
          { id: 8, name: "Birthday Flower 2", price: "500,000VND", image: "/birthday/bi8.jpg" },
      ],
  },
  {
      Id: 9,
      name: "DAISY",
      logo: "/image/logo9.jpg",
      address: "789 Daisy Drive, District 11, Ho Chi Minh City",
      type: "Seller",
      created_at: "2018-08-14",
      updated_at: "2022-01-05",
      role: "individual",
      introduction: "DAISY specializes in fresh and vibrant flowers, providing elegant floral arrangements for every occasion. We pride ourselves on delivering quality flowers and excellent customer service.",
      products: [
          { id: 1, name: "Rose 1", price: "400,000VND", image: "/roses/rose9.jpg" },
          { id: 2, name: "Birthday Flower", price: "500,000VND", image: "/birthday/bi9.jpg" },
          { id: 3, name: "Rose 2", price: "600,000VND", image: "/roses/rose9.jpg" },
          { id: 4, name: "Holiday Flower", price: "350,000VND", image: "/holiday/ho9.jpg" },
          { id: 5, name: "Orchid", price: "400,000VND", image: "/orchid/o9.jpg" },
          { id: 6, name: "Congratulate Flower", price: "400,000VND", image: "/congratulate/con9.jpg" },
          { id: 7, name: "Table Flower", price: "300,000VND", image: "/table/table9.jpg" },
          { id: 8, name: "Birthday Flower 2", price: "500,000VND", image: "/birthday/bi9.jpg" },
      ],
  },
  {
      Id: 10,
      name: "SWEET GARDEN",
      logo: "/image/logo10.jpg",
      address: "123 Garden Lane, District 12, Ho Chi Minh City",
      type: "Seller",
      created_at: "2016-05-12",
      updated_at: "2022-06-20",
      role: "enterprise",
      introduction: "SWEET GARDEN offers a beautiful selection of fresh flowers, specializing in floral arrangements for all events. With over 5 years of experience, we are passionate about delivering the best in quality and design.",
      products: [
          { id: 1, name: "Rose 1", price: "400,000VND", image: "/roses/rose10.jpg" },
          { id: 2, name: "Birthday Flower", price: "500,000VND", image: "/birthday/bi10.jpg" },
          { id: 3, name: "Rose 2", price: "600,000VND", image: "/roses/rose10.jpg" },
          { id: 4, name: "Holiday Flower", price: "350,000VND", image: "/holiday/ho10.jpg" },
          { id: 5, name: "Orchid", price: "400,000VND", image: "/orchid/o10.jpg" },
          { id: 6, name: "Congratulate Flower", price: "400,000VND", image: "/congratulate/con10.jpg" },
          { id: 7, name: "Table Flower", price: "300,000VND", image: "/table/table10.jpg" },
          { id: 8, name: "Birthday Flower 2", price: "500,000VND", image: "/birthday/bi10.jpg" },
      ],
  },
];
