export const sellerData = [
    {
      Id: 1,
      name: "FLORA",
      logo: "/image/Logo-shop-hoa-2.jpg",
      followers: "29k",
      rating: 4.8,
      reviews: "45.9k",
      joined: "4 years ago",
      products: [
        { id: 1, name: "Rose 1", price: "400,000VND", image: "/roses/rose1.jpg" },
        { id: 2, name: "Birthday FLower", price: "500,000VND", image: "/birthday/bi1.jpg" },
        { id: 3, name: "Rose 2", price: "600,000VND", image: "/roses/rose2.jpg" },
        { id: 4, name: "Holiday FLower", price: "350,000VND", image: "/holiday/ho1.jpg" },
        { id: 5, name: "Orchid", price: "400,000VND", image: "/orchid/o12.jpg" },
        { id: 6, name: "Congratulate FLower", price: "400,000VND", image: "/congratulate/con15.jpg" },
        { id: 7, name: "Table Flower", price: "300,000VND", image: "/table/table18.jpg" },
        { id: 8, name: "Birthday FLower 2", price: "500,000VND", image: "/birthday/bi7.jpg" },
      ],
    },
    {
      Id: 2,
      name: "SENTIMENT",
      logo: "/image/logo2.jpg",
      followers: "15k",
      rating: 4.6,
      reviews: "30.1k",
      joined: "3 years ago",
      products: [
        { id: 1, name: "Rose 1", price: "400,000VND", image: "/roses/rose15.jpg" },
        { id: 2, name: "Birthday FLower", price: "500,000VND", image: "/birthday/bi11.jpg" },
        { id: 3, name: "Rose 2", price: "600,000VND", image: "/roses/rose9.jpg" },
        { id: 4, name: "Holiday FLower", price: "350,000VND", image: "/holiday/ho3.jpg" },
        { id: 5, name: "Orchid", price: "400,000VND", image: "/orchid/o14.jpg" },
        { id: 6, name: "Congratulate FLower", price: "400,000VND", image: "/congratulate/con12.jpg" },
        { id: 7, name: "Table Flower", price: "300,000VND", image: "/table/table14.jpg" },
        { id: 8, name: "Birthday FLower 2", price: "500,000VND", image: "/birthday/bi3.jpg" },
      ],
    },
    {
      Id: 3,
      name: "DARIANA",
      logo: "/image/logo3.png",
      followers: "20k",
      rating: 4.9,
      reviews: "40.2k",
      joined: "5 years ago",
      products: [
        { id: 1, name: "Rose 1", price: "400,000VND", image: "/roses/rose2.jpg" },
        { id: 2, name: "Birthday FLower", price: "500,000VND", image: "/birthday/bi7.jpg" },
        { id: 3, name: "Rose 2", price: "600,000VND", image: "/roses/rose6.jpg" },
        { id: 4, name: "Holiday FLower", price: "350,000VND", image: "/holiday/ho9.jpg" },
        { id: 5, name: "Orchid", price: "400,000VND", image: "/orchid/o3.jpg" },
        { id: 6, name: "Congratulate FLower", price: "400,000VND", image: "/congratulate/con12.jpg" },
        { id: 7, name: "Table Flower", price: "300,000VND", image: "/table/table17.jpg" },
        { id: 8, name: "Birthday FLower 2", price: "500,000VND", image: "/birthday/bi8.jpg" },
      ],
    },
    {
      Id: 4,
      name: "FLORIFFIC",
      logo: "/image/logo4.png",
      followers: "22k",
      rating: 4.7,
      reviews: "32.8k",
      joined: "3.5 years ago",
      products: [
        { id: 1, name: "Rose 1", price: "400,000VND", image: "/roses/rose4.jpg" },
        { id: 2, name: "Birthday FLower", price: "500,000VND", image: "/birthday/bi4.jpg" },
        { id: 3, name: "Rose 2", price: "600,000VND", image: "/roses/rose4.jpg" },
        { id: 4, name: "Holiday FLower", price: "350,000VND", image: "/holiday/ho4.jpg" },
        { id: 5, name: "Orchid", price: "400,000VND", image: "/orchid/o4.jpg" },
        { id: 6, name: "Congratulate FLower", price: "400,000VND", image: "/congratulate/con4.jpg" },
        { id: 7, name: "Table Flower", price: "300,000VND", image: "/table/table4.jpg" },
        { id: 8, name: "Birthday FLower 2", price: "500,000VND", image: "/birthday/bi4.jpg" },
      ],
    },
    {
      Id: 5,
      name: "FLORAL FANTASY",
      logo: "/image/logo5.jpg",
      followers: "12k",
      rating: 4.5,
      reviews: "20.3k",
      joined: "2 years ago",
      products: [
        { id: 1, name: "Rose 1", price: "400,000VND", image: "/roses/rose5.jpg" },
        { id: 2, name: "Birthday FLower", price: "500,000VND", image: "/birthday/bi5.jpg" },
        { id: 3, name: "Rose 2", price: "600,000VND", image: "/roses/rose5.jpg" },
        { id: 4, name: "Holiday FLower", price: "350,000VND", image: "/holiday/ho5.jpg" },
        { id: 5, name: "Orchid", price: "400,000VND", image: "/orchid/o5.jpg" },
        { id: 6, name: "Congratulate FLower", price: "400,000VND", image: "/congratulate/con5.jpg" },
        { id: 7, name: "Table Flower", price: "300,000VND", image: "/table/table5.jpg" },
        { id: 8, name: "Birthday FLower 2", price: "500,000VND", image: "/birthday/bi5.jpg" },
      ],
    },
    {
      Id: 6,
      name: "PENNY",
      logo: "/image/logo6.jpg",
      followers: "18k",
      rating: 4.8,
      reviews: "28.7k",
      joined: "3.5 years ago",
      products: [
        { id: 1, name: "Rose 1", price: "400,000VND", image: "/roses/rose6.jpg" },
        { id: 2, name: "Birthday FLower", price: "500,000VND", image: "/birthday/bi6.jpg" },
        { id: 3, name: "Rose 2", price: "600,000VND", image: "/roses/rose6.jpg" },
        { id: 4, name: "Holiday FLower", price: "350,000VND", image: "/holiday/ho6.jpg" },
        { id: 5, name: "Orchid", price: "400,000VND", image: "/orchid/o6.jpg" },
        { id: 6, name: "Congratulate FLower", price: "400,000VND", image: "/congratulate/con6.jpg" },
        { id: 7, name: "Table Flower", price: "300,000VND", image: "/table/table6.jpg" },
        { id: 8, name: "Birthday FLower 2", price: "500,000VND", image: "/birthday/bi6.jpg" },
      ],
    },
    {
      Id: 7,
      name: "CAROLINA PETALS",
      logo: "/image/logo7.jpg",
      followers: "10k",
      rating: 4.6,
      reviews: "18.2k",
      joined: "2.5 years ago",
      products: [
        { id: 1, name: "Rose 1", price: "400,000VND", image: "/roses/rose7.jpg" },
        { id: 2, name: "Birthday FLower", price: "500,000VND", image: "/birthday/bi7.jpg" },
        { id: 3, name: "Rose 2", price: "600,000VND", image: "/roses/rose7.jpg" },
        { id: 4, name: "Holiday FLower", price: "350,000VND", image: "/holiday/ho7.jpg" },
        { id: 5, name: "Orchid", price: "400,000VND", image: "/orchid/o7.jpg" },
        { id: 6, name: "Congratulate FLower", price: "400,000VND", image: "/congratulate/con7.jpg" },
        { id: 7, name: "Table Flower", price: "300,000VND", image: "/table/table7.jpg" },
        { id: 8, name: "Birthday FLower 2", price: "500,000VND", image: "/birthday/bi10.jpg" },
      ],
    },
    {
      Id: 8,
      name: "CERDARHHOUSE",
      logo: "/image/logo8.jpg",
      followers: "25k",
      rating: 4.9,
      reviews: "35.5k",
      joined: "4 years ago",
      products: [
        { id: 1, name: "Rose 1", price: "400,000VND", image: "/roses/rose8.jpg" },
        { id: 2, name: "Birthday FLower", price: "500,000VND", image: "/birthday/bi8.jpg" },
        { id: 3, name: "Rose 2", price: "600,000VND", image: "/roses/rose8.jpg" },
        { id: 4, name: "Holiday FLower", price: "350,000VND", image: "/holiday/ho8.jpg" },
        { id: 5, name: "Orchid", price: "400,000VND", image: "/orchid/o8.jpg" },
        { id: 6, name: "Congratulate FLower", price: "400,000VND", image: "/congratulate/con8.jpg" },
        { id: 7, name: "Table Flower", price: "300,000VND", image: "/table/table8.jpg" },
        { id: 8, name: "Birthday FLower 2", price: "500,000VND", image: "/birthday/bi8.jpg" },
      ],
    },
    {
      Id: 9,
      name: "DAISY",
      logo: "/image/logo9.jpg",
      followers: "16k",
      rating: 4.7,
      reviews: "27.9k",
      joined: "3 years ago",
      products: [
        { id: 1, name: "Rose 1", price: "400,000VND", image: "/roses/rose9.jpg" },
        { id: 2, name: "Birthday FLower", price: "500,000VND", image: "/birthday/bi9.jpg" },
        { id: 3, name: "Rose 2", price: "600,000VND", image: "/roses/rose9.jpg" },
        { id: 4, name: "Holiday FLower", price: "350,000VND", image: "/holiday/ho9.jpg" },
        { id: 5, name: "Orchid", price: "400,000VND", image: "/orchid/o9.jpg" },
        { id: 6, name: "Congratulate FLower", price: "400,000VND", image: "/congratulate/con9.jpg" },
        { id: 7, name: "Table Flower", price: "300,000VND", image: "/table/table9.jpg" },
        { id: 8, name: "Birthday FLower 2", price: "500,000VND", image: "/birthday/bi9.jpg" },
      ],
    },
    {
      Id: 10,
      name: "SWEET GARDEN",
      logo: "/image/logo10.jpg",
      followers: "30k",
      rating: 4.9,
      reviews: "50.6k",
      joined: "5 years ago",
      products: [
        { id: 1, name: "Rose 1", price: "400,000VND", image: "/roses/rose10.jpg" },
        { id: 2, name: "Birthday FLower", price: "500,000VND", image: "/birthday/bi10.jpg" },
        { id: 3, name: "Rose 2", price: "600,000VND", image: "/roses/rose10.jpg" },
        { id: 4, name: "Holiday FLower", price: "350,000VND", image: "/holiday/ho10.jpg" },
        { id: 5, name: "Orchid", price: "400,000VND", image: "/orchid/o10.jpg" },
        { id: 6, name: "Congratulate FLower", price: "400,000VND", image: "/congratulate/con10.jpg" },
        { id: 7, name: "Table Flower", price: "300,000VND", image: "/table/table10.jpg" },
        { id: 8, name: "Birthday FLower 2", price: "500,000VND", image: "/birthday/bi10.jpg" },
      ],
    }
  ];
  